version: '3.8'

services:
  # Nuxt 应用
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-fullstack-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    depends_on:
      - redis
    networks:
      - nuxt-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # Redis 缓存
  redis:
    image: redis:7.2-alpine
    container_name: nuxt-fullstack-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nuxt-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: nuxt-fullstack-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - nuxt-app
    networks:
      - nuxt-network
    restart: unless-stopped

networks:
  nuxt-network:
    driver: bridge

volumes:
  redis_data: 